apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1    
  name: worker-1
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: KubeadmConfig
      name: worker-1-config
      namespace: default
  clusterName: ibm-vpc-1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: IBMVPCMachine
    name: worker-1
    namespace: default
  version: v1.14.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: IBMVPCMachine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
  name: worker-1
spec:
  name: worker-1
  image: r134-ea84bbec-7986-4ff5-8489-d9ec34611dd4
  zone: us-south-1
  profile: bx2-4x16
  sshKeys:
  - "r134-2a82b725-e570-43d3-8b23-9539e8641944"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfig
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
  name: worker-1-config
  namespace: default
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%