apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
    cluster.x-k8s.io/control-plane: ""  
  name: controlplane-1
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: KubeadmConfig
      name: controlplane-1-config
      namespace: default
  clusterName: ibm-vpc-1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: IBMVPCMachine
    name: controlplane-1
    namespace: default
  version: v1.14.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: IBMVPCMachine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
    cluster.x-k8s.io/control-plane: "true"  
  name: controlplane-1
spec:
  name: controlplane-1
  image: r134-ea84bbec-7986-4ff5-8489-d9ec34611dd4
  zone: us-south-1
  profile: bx2-4x16
  sshKeys:
  - "r134-2a82b725-e570-43d3-8b23-9539e8641944"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfig
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
    cluster.x-k8s.io/control-plane: ""
  name: controlplane-1-config
  namespace: default
spec:
  clusterConfiguration:
    apiServer:
      certSANs:
      - localhost
      - 127.0.0.1
    clusterName: ibm-vpc-1
    controllerManager:
      extraArgs:
        enable-hostpath-provisioner: "true"
    dns: {}
    etcd: {}
    kubernetesVersion: v1.14.3
    networking:
      dnsDomain: cluster.local
      podSubnet: 192.168.0.0/16
      serviceSubnet: 10.128.0.0/12
    scheduler: {}
  initConfiguration:
    localAPIEndpoint:
      advertiseAddress: ""
      bindPort: 0
    nodeRegistration:
      criSocket: /var/run/containerd/containerd.sock
      kubeletExtraArgs:
        eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: IBMVPCMachineTemplate
metadata:
  name: ibm-vpc-1-control-plane
  namespace: default
spec:
  template:
    spec:
      name: controlplane-1
      image: r134-ea84bbec-7986-4ff5-8489-d9ec34611dd4
      zone: us-south-1
      profile: bx2-4x16
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-vpc-1
  name: ibm-vpc-1-control-plane
  namespace: default
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: IBMVPCMachineTemplate
    name: ibm-vpc-1-control-plane
    namespace: default
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
      controllerManager: 
        extraArgs:
          enable-hostpath-provisioner: "true"
      dns: {}
      etcd: {}
      networking: {}
      scheduler: {}
    initConfiguration:
      localAPIEndpoint:
        advertiseAddress: ""
        bindPort: 0
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      discovery: {}
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  replicas: 1
  version: v1.14.3